# Generated by Django 5.2.3 on 2026-06-25 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_id', models.UUIDField(editable=False)),
                ('test_case_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_id', models.UUIDField(editable=False, null=True)),
                ('qa_model_used', models.CharField(blank=True, max_length=1000, null=True)),
                ('validation_model_used', models.CharField(blank=True, max_length=1000, null=True)),
                ('aggregate_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_input', models.TextField(blank=True, null=True)),
                ('retrieved_contexts', models.JSONField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('faithfulness', models.FloatField(blank=True, null=True)),
                ('answer_relevancy', models.FloatField(blank=True, null=True)),
                ('answer_correctness', models.FloatField(blank=True, null=True)),
                ('context_recall', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseDBAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_case_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_id', models.UUIDField(editable=False, null=True)),
                ('qa_model_used', models.CharField(blank=True, max_length=1000, null=True)),
                ('validation_model_used', models.CharField(blank=True, max_length=1000, null=True)),
                ('aggregate_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('number_of_testcases', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
