# Generated by Django 5.2.3 on 2026-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasedb',
            old_name='retrieved_contexts',
            new_name='retrieved_context_array',
        ),
        migrations.AddField(
            model_name='testcasedb',
            name='answer_correctness_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcasedb',
            name='answer_relevancy_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcasedb',
            name='context_recall_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcasedb',
            name='faithfulness_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcasedb',
            name='retrieved_context_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
