# Generated by Django 5.2.3 on 2025-07-12 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.UUIDField(editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=30000)),
                ('answer', models.CharField(max_length=30000)),
                ('agent_calls', models.JSONField()),
                ('retrieved_doc_ids', models.JSONField()),
                ('status_code', models.IntegerField()),
                ('request_time_seconds', models.IntegerField()),
                ('times_per_service', models.JSONField()),
            ],
        ),
    ]
