# Generated by Django 5.2.3 on 2025-07-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='contact_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
