# Generated by Django 5.2.3 on 2025-07-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_messagehistory_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
