# Generated by Django 5.2.3 on 2026-05-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chathistory_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='user_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='user_id',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
