# Generated by Django 5.2.3 on 2026-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embed', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorsearch1536',
            name='namespace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vectorsearch2048',
            name='namespace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vectorsearch3072',
            name='namespace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
