# Generated by Django 5.2.3 on 2026-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embed', '0003_vectorsearch1536_namespace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVectorMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(editable=False, null=True)),
                ('namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
