# Generated by Django 5.2.3 on 2026-05-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embed', '0004_uservectormetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservectormetadata',
            name='namespace_type',
            field=models.CharField(blank=True, help_text="Type of the namespace, e.g., 'supabase', 'pinecone', etc.", max_length=100, null=True),
        ),
    ]
