# Generated by Django 5.2.3 on 2026-05-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embed', '0005_uservectormetadata_namespace_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservectormetadata',
            name='supabase_table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
