# Generated by Django 5.2.3 on 2026-06-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embed', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION update_search_vector_1536()
            RETURNS TRIGGER AS $$
            BEGIN
            NEW.search_vector := setweight(to_tsvector('english', coalesce(NEW.content, '')), 'A');
            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS vector_search_1536_update ON embed_vectorsearch1536;

            CREATE TRIGGER vector_search_1536_update
            BEFORE INSERT OR UPDATE ON embed_vectorsearch1536
            FOR EACH ROW EXECUTE FUNCTION update_search_vector_1536();

            CREATE OR REPLACE FUNCTION update_search_vector_2048()
            RETURNS TRIGGER AS $$
            BEGIN
            NEW.search_vector := setweight(to_tsvector('english', coalesce(NEW.content, '')), 'A');
            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS vector_search_2048_update ON embed_vectorsearch2048;

            CREATE TRIGGER  vector_search_2048_update
            BEFORE INSERT OR UPDATE ON embed_vectorsearch2048
            FOR EACH ROW EXECUTE FUNCTION update_search_vector_2048();

            CREATE OR REPLACE FUNCTION update_search_vector_3072()
            RETURNS TRIGGER AS $$
            BEGIN
            NEW.search_vector := setweight(to_tsvector('english', coalesce(NEW.content,'')), 'A');
            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS vector_search_3072_update ON embed_vectorsearch3072;

            CREATE TRIGGER vector_search_3072_update
            BEFORE INSERT OR UPDATE ON embed_vectorsearch3072
            FOR EACH ROW EXECUTE FUNCTION update_search_vector_3072();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS vector_search_1536_update ON embed_vectorsearch1536;
            DROP FUNCTION IF EXISTS update_search_vector_1536();    

            DROP TRIGGER IF EXISTS vector_search_2048_update ON embed_vectorsearch2048;
            DROP FUNCTION IF EXISTS update_search_vector_2048();

            DROP TRIGGER IF EXISTS vector_search_3072_update ON embed_vectorsearch3072;
            DROP FUNCTION IF EXISTS update_search_vector_3072();
            """
        )
    ]
