# Generated by Django 5.2.3 on 2026-05-25 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('auth_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('surname', models.CharField(blank=True, max_length=150, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('user_premissions', models.JSONField(blank=True, null=True)),
                ('salt_string', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('log_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.usertable', to_field='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_metadata_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pine_cone_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('groq_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('mistral_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('cohere_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('jina_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.usertable', to_field='user_id')),
            ],
        ),
    ]
