# Generated by Django 5.2.3 on 2026-06-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='log_type',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
