# Note that Redis will write a pid file in /var/run/redis.pid when daemonized.
port 6379

maxmemory 500mb 
maxmemory-policy allkeys-lru

maxclients 1000
requirepass changeyourpasswordhere

save 900 1    
save 300 10  

appendonly yes
auto-aof-rewrite-min-size 32mb

