# Generated by Django 5.2.3 on 2025-12-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='user_premissions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
