# Generated by Django 5.2.3 on 2025-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_usertable_user_premissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='salt_string',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
