# Generated by Django 5.2.3 on 2026-03-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_usertable_salt_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pine_cone_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('groq_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('mistral_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('cohere_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('jina_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.usertable', to_field='user_id')),
            ],
        ),
    ]
