# Generated by Django 5.2.3 on 2026-03-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='user_name',
        ),
        migrations.AddField(
            model_name='usertable',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
