# Generated by Django 5.2.3 on 2026-03-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_remove_usertable_user_name_usertable_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
